from django.contrib import admin
from django.urls import path, include
from .views import (
    base, home, report_gbv, resources, contact, contribute, about,
    education, blog_details, article_detail, emergency,
    privacy_policy, terms_of_service,
    ai_chat, ai_chat_delete_thread,
    contribute_article, contribute_blog, contribute_story,
    contribute_resource, contribute_idea,
    resource_navigate, route_api, resources_map, admin_metrics_api,
    admin_gbv_sla_api, export_gbv_reports_csv, export_support_feedback_csv,
    export_gbv_sla_csv, export_articles_csv, export_blogs_csv,
    export_contacts_csv, export_users_csv, export_audit_logs_csv,
    export_ai_reports_csv,
    # Authentication
    login_view, signup_view, logout_view,
    verify_email_view, resend_code_view, verify_mfa_view,
    forgot_password_view, reset_password_view,
    myprofile_view,
    change_role_view,
    my_contributions_view,
    # Reports
    report_timeline, support_feedback,
)

urlpatterns = [
    path("", home, name="home"),
    path('base/', base, name='base'),

    path("report-gbv/", report_gbv, name="report_gbv"),
    path("education/", education, name="education"),
    path("resources/", resources, name="resources"),
    path("contribute/", contribute, name="contribute"),
    path("about/", about, name="about"),
    path("privacy-policy/", privacy_policy, name="privacy_policy"),
    path("terms-of-service/", terms_of_service, name="terms_of_service"),
    path("contact/", contact, name="contact"),
    path("blog_detail/<int:id>/", blog_details, name="blog_detail"),
    path("article_detail/<int:id>/", article_detail, name="article_detail"),
    path("emergency/", emergency, name="emergency"),
    path("ai-chat/", ai_chat, name="ai_chat"),
    path("ai-chat/thread/<int:thread_id>/delete/", ai_chat_delete_thread, name="ai_chat_delete_thread"),
    path("resources/map/", resources_map, name="resources_map"),
    path("resource/<int:id>/navigate/", resource_navigate, name="resource_navigate"),
    path("api/route/", route_api, name="route_api"),
    path("api/admin-metrics/", admin_metrics_api, name="admin_metrics_api"),
    path("api/admin-reports/gbv-sla.json", admin_gbv_sla_api, name="admin_gbv_sla_api"),
    path("api/admin-reports/gbv.csv", export_gbv_reports_csv, name="export_gbv_reports_csv"),
    path("api/admin-reports/support-feedback.csv", export_support_feedback_csv, name="export_support_feedback_csv"),
    path("api/admin-reports/gbv-sla.csv", export_gbv_sla_csv, name="export_gbv_sla_csv"),
    path("api/admin-reports/articles.csv", export_articles_csv, name="export_articles_csv"),
    path("api/admin-reports/blogs.csv", export_blogs_csv, name="export_blogs_csv"),
    path("api/admin-reports/contacts.csv", export_contacts_csv, name="export_contacts_csv"),
    path("api/admin-reports/users.csv", export_users_csv, name="export_users_csv"),
    path("api/admin-reports/logs.csv", export_audit_logs_csv, name="export_audit_logs_csv"),
    path("api/admin-reports/ai-reports.csv", export_ai_reports_csv, name="export_ai_reports_csv"),
    path("reports/<int:report_id>/timeline/", report_timeline, name="report_timeline"),
    path("reports/<int:report_id>/feedback/", support_feedback, name="support_feedback"),

    # Authentication
    path("login/", login_view, name="login"),
    path("signup/", signup_view, name="signup"),
    path("logout/", logout_view, name="logout"),
    path("verify-email/", verify_email_view, name="verify_email"),
    path("resend-code/", resend_code_view, name="resend_code"),
    path("verify-mfa/", verify_mfa_view, name="verify_mfa"),
    path("forgot-password/", forgot_password_view, name="forgot_password"),
    path("reset-password/", reset_password_view, name="reset_password"),
    path("myprofile/", myprofile_view, name="myprofile"),
    path("change-role/", change_role_view, name="change_role"),
    path("my-contributions/", my_contributions_view, name="my_contributions"),
    path("contribute/article/", contribute_article, name="contribute_article"),
    path("contribute/blog/", contribute_blog, name="contribute_blog"),
    path("contribute/story/", contribute_story, name="contribute_story"),
    path("contribute/resource/", contribute_resource, name="contribute_resource"),
    path("contribute/idea/", contribute_idea, name="contribute_idea"),
]
