# Generated by Django 6.0.1 on 2026-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voices', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
