# Generated by Django 6.0.1 on 2026-02-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voices', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
