# Generated by Django 6.0.1 on 2026-02-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voices', '0006_blog_read_time_blog_updated_at_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
