# Generated by Django 6.0.1 on 2026-03-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voices', '0012_content_readiness_upgrades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gbvreportstatusupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('prevention', 'Prevention'), ('support', 'Support Services'), ('legal', 'Legal Rights'), ('awareness', 'Awareness'), ('recovery', 'Recovery & Healing'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('prevention', 'Prevention'), ('support', 'Support Services'), ('legal', 'Legal Rights'), ('awareness', 'Awareness'), ('recovery', 'Recovery & Healing'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
