# Generated by Django 6.0.1 on 2026-03-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voices', '0013_add_recovery_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlereadingprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articlereadingprogress',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlereadingprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArticleBookmark',
        ),
        migrations.DeleteModel(
            name='ArticleReadingProgress',
        ),
    ]
