# Generated by Django 6.0.1 on 2026-04-11 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voices', '0014_remove_bookmark_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationStory',
        ),
        migrations.AlterModelOptions(
            name='supportfeedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='story',
            name='name',
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
