# Generated by Django 6.0.1 on 2026-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voices', '0016_remove_idea_email_remove_idea_name_contact_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbvreport',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gbvreport',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('prefer_not', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gbvreport',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gbvreport',
            name='relationship_to_perpetrator',
            field=models.CharField(blank=True, choices=[('partner', 'Intimate Partner / Spouse'), ('family', 'Family Member'), ('acquaintance', 'Acquaintance / Neighbour'), ('employer', 'Employer / Authority Figure'), ('stranger', 'Stranger'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('victim', 'Reporter'), ('contributor', 'Contributor')], default='victim', max_length=20),
        ),
    ]
