"""
Django settings for VAV project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

try:
    import dj_database_url as _dj_database_url
    _HAS_DJ_DATABASE_URL = True
except ImportError:
    _HAS_DJ_DATABASE_URL = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env_file(env_path: Path) -> None:
    if not env_path.exists():
        return
    for raw_line in env_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name: str, default=None):
    if default is None:
        default = []
    raw = os.environ.get(name)
    if not raw:
        return default
    return [item.strip() for item in raw.split(',') if item.strip()]


_load_local_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me-in-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', default=True)

if not DEBUG and SECRET_KEY == 'django-insecure-change-me-in-env':
    raise RuntimeError('Set SECRET_KEY in environment when DEBUG is False.')

_DEFAULT_ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '35.171.79.126',
    'voicesagainstviolence.co.ke',
    'www.voicesagainstviolence.co.ke',
]
ALLOWED_HOSTS = sorted(set(_DEFAULT_ALLOWED_HOSTS + _env_list('ALLOWED_HOSTS', default=[])))
_DEFAULT_CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
]
CSRF_TRUSTED_ORIGINS = sorted(
    set(_DEFAULT_CSRF_TRUSTED_ORIGINS + _env_list('CSRF_TRUSTED_ORIGINS', default=[]))
)


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_summernote',
    'whitenoise.runserver_nostatic',
    'django_ai_assistant',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'Voices.apps.VoicesConfig',
]

JAZZMIN_SETTINGS = {
    'site_title': 'VAV Admin',
    'site_header': 'Voices Against Violence',
    'site_brand': 'VAV Admin',
    'welcome_sign': 'Welcome to Voices Against Violence Admin',
    'copyright': 'Voices Against Violence',
    'custom_css': 'assets/css/admin-jazzmin.css',
    'custom_js': 'assets/js/admin-jazzmin.js',
    'show_ui_builder': False,
    'show_sidebar': True,
    'navigation_expanded': True,
    'changeform_format': 'horizontal_tabs',
    'language_chooser': False,
    'topmenu_links': [
        {'name': 'View Site', 'url': 'home', 'new_window': True, 'icon': 'fas fa-external-link-alt'},
        {'name': 'Resources Map', 'url': 'resources_map', 'new_window': True, 'icon': 'fas fa-map'},
    ],
    'order_with_respect_to': [
        'Voices',
        'auth',
    ],
    'icons': {
        'Voices': 'fas fa-microphone-alt',
        'Voices.resource': 'fas fa-map-marker-alt',
        'Voices.gbvreport': 'fas fa-shield-alt',
        'Voices.gbvreportstatusupdate': 'fas fa-tasks',
        'Voices.article': 'fas fa-newspaper',
        'Voices.blog': 'fas fa-blog',
        'Voices.story': 'fas fa-book-open',
        'Voices.idea': 'fas fa-lightbulb',
        'Voices.contact': 'fas fa-envelope',
        'Voices.team': 'fas fa-users',
        'Voices.userprofile': 'fas fa-id-badge',
        'Voices.auditlog': 'fas fa-history',
        'Voices.supportfeedback': 'fas fa-comments',
        'auth': 'fas fa-lock',
        'auth.user': 'fas fa-user-cog',
        'auth.group': 'fas fa-users-cog',
    },
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
    'dark_mode_theme': 'darkly',
    'navbar': 'navbar-purple',
    'accent': 'accent-purple',
    'sidebar': 'sidebar-dark-purple',
    'brand_colour': 'navbar-purple',
    'navbar_fixed': True,
    'sidebar_fixed': True,
    'sidebar_nav_small_text': False,
    'body_small_text': False,
    'footer_small_text': True,
    'button_classes': {
        'primary': 'btn-purple',
        'secondary': 'btn-outline-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'Voices.middleware.FirstVisitLoginGateMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "Voices.middleware.SimpleRateLimitMiddleware",
]

RATE_LIMIT_MAX_REQUESTS = 30
RATE_LIMIT_WINDOW_SECONDS = 60
RATE_LIMIT_PATH_PREFIXES = ("/signup", "/login", "/verify", "/report")

ROOT_URLCONF = 'VAV.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'VAV.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use DATABASE_URL env var if set (RDS on EB), fall back to SQLite for local dev
_DATABASE_URL = os.environ.get('DATABASE_URL')
if _DATABASE_URL and _HAS_DJ_DATABASE_URL:
    DATABASES = {'default': _dj_database_url.config(default=_DATABASE_URL, conn_max_age=600, ssl_require=True)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login URL
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# AWS Cognito
AWS_COGNITO_USER_POOL_ID      = os.environ.get('AWS_COGNITO_USER_POOL_ID')
AWS_COGNITO_APP_CLIENT_ID     = os.environ.get('AWS_COGNITO_APP_CLIENT_ID')
AWS_COGNITO_APP_CLIENT_SECRET = os.environ.get('AWS_COGNITO_APP_CLIENT_SECRET')
AWS_COGNITO_REGION            = os.environ.get('AWS_COGNITO_REGION', 'eu-north-1')

# Session
SESSION_COOKIE_AGE      = 3600
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE   = _env_bool('SESSION_COOKIE_SECURE', default=not DEBUG)

CACHES = {
    'default': {
        'BACKEND': os.environ.get('CACHE_BACKEND', 'django.core.cache.backends.locmem.LocMemCache'),
        'LOCATION': os.environ.get('CACHE_LOCATION', 'vav-local-cache'),
    }
}

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@voicesagainstviolence.ke')

# CSRF / HTTPS
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_HTTPONLY = _env_bool('CSRF_COOKIE_HTTPONLY', default=True)
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = _env_bool('SECURE_CONTENT_TYPE_NOSNIFF', default=True)
SECURE_REFERRER_POLICY = os.environ.get('SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')
X_FRAME_OPTIONS = os.environ.get('X_FRAME_OPTIONS', 'DENY')

# Resource mapping focus
RESOURCE_DEFAULT_COUNTY = os.environ.get('RESOURCE_DEFAULT_COUNTY', 'Nakuru County')

# Groq / AI assistant configuration
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_BASE_URL = os.environ.get('GROQ_BASE_URL', 'https://api.groq.com/openai/v1')
GBV_AI_MODEL = os.environ.get('GBV_AI_MODEL', 'llama-3.3-70b-versatile')

# django-ai-assistant permissions (default: users can only manage their own threads/messages)
AI_ASSISTANT_INIT_API_FN = 'django_ai_assistant.api.views.init_api'
AI_ASSISTANT_CAN_CREATE_THREAD_FN = 'Voices.ai_permissions.is_authenticated_user'
AI_ASSISTANT_CAN_VIEW_THREAD_FN = 'django_ai_assistant.permissions.owns_thread'
AI_ASSISTANT_CAN_UPDATE_THREAD_FN = 'django_ai_assistant.permissions.owns_thread'
AI_ASSISTANT_CAN_DELETE_THREAD_FN = 'django_ai_assistant.permissions.owns_thread'
AI_ASSISTANT_CAN_CREATE_MESSAGE_FN = 'django_ai_assistant.permissions.owns_thread'
AI_ASSISTANT_CAN_UPDATE_MESSAGE_FN = 'django_ai_assistant.permissions.owns_thread'
AI_ASSISTANT_CAN_DELETE_MESSAGE_FN = 'django_ai_assistant.permissions.owns_thread'
AI_ASSISTANT_CAN_RUN_ASSISTANT = 'Voices.ai_permissions.is_authenticated_user'